export enum ProductActionTypes {
  ADD_PRODUCT = '[Product] ADD PRODUCT',
  DELETE_PRODUCT = '[Product] DELETE PRODUCT',
  LOAD_PRODUCTS = '[Products] LOAD PRODUCTS',
  LOAD_PRODUCTS_SUCCESS = '[Products] LOAD PRODUCTS SUCCESS',
  LOAD_PRODUCTS_FAILURE = '[Products] LOAD PRODUCTS FAILURE',
}
